### ISSUE TITLE
[FritzBox TR-064] Can´t get WAN IP address

### ISSUE THREAD

**Issue by bredmich** [openhab/openhab1-addons#5283] opened 2017-08-22 16:42 UTC
Hi!

There´s an problem with the FritzBox TR-064 binding that results in some errors when trying to get the current WAN IP address.

The openHAB log says:
`2017-08-22 15:59:23.920 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - FritzBox returned unexpected response. Could not find expected datavalue NewExternalIPAddress in response <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:dslforum-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription>Invalid Action</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>`

It seems like the binding is trying to get the value at an now unknown place.

## Possible Solution
All informations for TR-064 can be found at AVM.
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wancommonifconfigSCPD.pdf

## Steps to Reproduce (for bugs)
1. Add the org.openhab.binding.fritzboxtr064-1.9.0-SNAPSHOT.jar binding
2. Configure the openhab.cfg
3. Add the item to default.items
`String fbWAN "IP-Adresse: [%s]" <fritzbox> {fritzboxtr064="wanip"}`
4. Add the item to the sitemap
`Text item=fbWAN`
5. Get the error in the openhab.log

## Context
I´m not able to get my current IP address and send messages when my current IP address changes.

## Your Environment
* Version used: openHAB 1.8.3 / FritzBox TR-064 binding 1.9.0 SNAPSHOT

**Comment by 9037568** [comment] 2017-08-24 23:26
Can you provide a debug log for this scenario?

**Comment by bredmich** [comment] 2017-08-25 05:34
Sure, going to post the log later.

**Comment by bredmich** [comment] 2017-08-28 13:43
Just checked the DEBUG loglevel and there´s no additional information. Just the same error as before:
`2017-08-28 15:24:43.460 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - FritzBox returned unexpected response. Could not find expected datavalue NewExternalIPAddress in response <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:dslforum-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription>Invalid Action</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>`

Seems like the logging capabilites of the FritzBoxTR064 binding aren´t enough...

**Comment by 9037568** [comment] 2017-08-28 22:54
Then you've set the logging incorrectly.

There's a [DEBUG message](https://github.com/openhab/openhab1-addons/blob/1.9.x/bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java#L234) that would occur immediately following the error you're seeing.

Show how you configured the logging.

**Comment by bredmich** [comment] 2017-08-29 16:01
This three lines are coming right after the unexpected response:
`2017-08-28 15:24:43.467 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - call monitor is not running. Configured items require call monitor -> Starting call monitor...
2017-08-28 15:24:43.469 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Downloading phonebooks
2017-08-28 15:24:43.480 [INFO ] [o.o.b.f.i.FritzboxTr064Binding] - Downloading phonebook ID 0`

I set the DEBUG log in the logback.xml:
`<logger name="org.openhab" level="DEBUG"/>`

Pastebin of the whole log:
https://pastebin.com/F0GV1vQ8
(Hopefully i removed everything that´s not for public eyes)

FritzBox = 192.168.2.1
openHAB = 192.168.2.8

The binding is trying to get the value "WANPPPConnection".
I´m not sure if this is the right value for my setup.
I´m not using the internal DSL modem, i´m using an external cable modem connected to the WAN port. My FritzBox gets the public IPv4 from my modem.
Maybe the value is "WANIPConnection"...

Check: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf
6.1.15: WANPPPConnection
6.1.16: WANIPConnection

Cheers

**Comment by 9037568** [comment] 2017-08-30 03:24
According to [this thread](https://kb.paessler.com/en/topic/38603-how-do-i-activate-upnp-for-my-fritz-box), the 401 Invalid Action error is due to a configuration problem on the Fritzbox. It appears you must do some setup to allow UPnP.

**Comment by bredmich** [comment] 2017-08-30 05:12
It's already active.

**Comment by 9037568** [comment] 2017-08-30 11:29
The specification you linked to also says:

````
    If an unknown action is used the returned code is 401. This return code is used for obsoleted actions, too
````

If I've understood section 3 correctly, you could try doing a manual discovery of services.

**Comment by bredmich** [comment] 2017-08-30 15:27
• DNS resolution of fritz.box
I´m not using the FritzBox internal DNS because it causes trouble with some clients.
Workaround: I´m going to add the fritz.box entry to my Raspberry hosts file.

• HTTP GET request to http://192.168.2.1:49000/tr64desc.xml
• HTTPS GET request to https://192.168.2.1:49443/tr64desc.xml
I´m able to open both websites.
The HTTPS website is using an self signed certificate and browsers don´t want to open this website without confirmation

**Comment by bredmich** [comment] 2017-08-30 15:43
Same error:
> 2017-08-30 17:40:56.340 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Raw SOAP Request to be sent to FritzBox: <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><u:GetExternalIPAddress xmlns:u="urn:dslforum-org:service:WANPPPConnection:1"/></SOAP-ENV:Body></SOAP-ENV:Envelope>
> 2017-08-30 17:40:56.418 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Releasing connection
> 2017-08-30 17:40:56.419 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Raw SOAP Response from FritzBox: <?xml version="1.0"?>
> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
> <s:Body>
> <s:Fault>
> <faultcode>s:Client</faultcode>
> <faultstring>UPnPError</faultstring>
> <detail>
> <UPnPError xmlns="urn:dslforum-org:control-1-0">
> <errorCode>401</errorCode>
> <errorDescription>Invalid Action</errorDescription>
> </UPnPError>
> </detail>
> </s:Fault>
> </s:Body>
> </s:Envelope>
> 2017-08-30 17:40:56.439 [ERROR] [o.o.b.f.i.FritzboxTr064Binding] - FritzBox returned unexpected response. Could not find expected datavalue NewExternalIPAddress in response <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
> <s:Body>
> <s:Fault>
> <faultcode>s:Client</faultcode>
> <faultstring>UPnPError</faultstring>
> <detail>
> <UPnPError xmlns="urn:dslforum-org:control-1-0">
> <errorCode>401</errorCode>
> <errorDescription>Invalid Action</errorDescription>
> </UPnPError>
> </detail>
> </s:Fault>
> </s:Body>
> </s:Envelope>

**Comment by 9037568** [comment] 2017-08-30 22:49
> • HTTP GET request to http://192.168.2.1:49000/tr64desc.xml
• HTTPS GET request to https://192.168.2.1:49443/tr64desc.xml
I´m able to open both websites.

The question is what you get when you open one. It should, in theory, tell you which actions are supported.

**Comment by 9037568** [comment] 2017-08-30 22:56
You might also wish to try [this test with curl](http://scytale.name/blog/2010/01/fritzbox-wan-ip) to see if you get a different response.

**Comment by bredmich** [comment] 2017-08-31 18:28
Both parameters are available:
`<service><serviceType>urn:dslforum-org:service:WANPPPConnection:1</serviceType><serviceId>urn:WANPPPConnection-com:serviceId:WANPPPConnection1</serviceId><controlURL>/upnp/control/wanpppconn1</controlURL><eventSubURL>/upnp/control/wanpppconn1</eventSubURL><SCPDURL>/wanpppconnSCPD.xml</SCPDURL></service><service><serviceType>urn:dslforum-org:service:WANIPConnection:1</serviceType><serviceId>urn:WANIPConnection-com:serviceId:WANIPConnection1</serviceId><controlURL>/upnp/control/wanipconnection1</controlURL><eventSubURL>/upnp/control/wanipconnection1</eventSubURL><SCPDURL>/wanipconnSCPD.xml</SCPDURL></service>`

I´m going to test the curl now.

**Comment by bredmich** [comment] 2017-08-31 18:36
Same error:

> pi@HER-MB-OpenHab:~ $ curl -s -H 'Content-Type: text/xml; charset="utf-8"' -H 'SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress' --data-binary '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1" /></s:Body></s:Envelope>' http://192.168.2.1:49000/upnp/control/WANCommonIFC1
> <?xml version="1.0"?>
> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
> <s:Body>
> <s:Fault>
> <faultcode>s:Client</faultcode>
> <faultstring>UPnPError</faultstring>
> <detail>
> <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
> <errorCode>401</errorCode>
> <errorDescription>Invalid Action</errorDescription>
> </UPnPError>
> </detail>
> </s:Fault>
> </s:Body>
> </s:Envelope>

**Comment by bredmich** [comment] 2017-08-31 18:37
Doesn´t matter if IP or PPP is used:

> pi@HER-MB-OpenHab:~ $ curl -s -H 'Content-Type: text/xml; charset="utf-8"' -H 'SOAPAction: urn:schemas-upnp-org:service:WANPPPConnection:1#GetExternalIPAddress' --data-binary '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANPPPConnection:1" /></s:Body></s:Envelope>' http://192.168.2.1:49000/upnp/control/WANCommonIFC1
> <?xml version="1.0"?>
> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
> <s:Body>
> <s:Fault>
> <faultcode>s:Client</faultcode>
> <faultstring>UPnPError</faultstring>
> <detail>
> <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
> <errorCode>401</errorCode>
> <errorDescription>Invalid Action</errorDescription>
> </UPnPError>
> </detail>
> </s:Fault>
> </s:Body>
> </s:Envelope>

**Comment by 9037568** [comment] 2017-09-01 01:03
Recommend the next step should be asking in the [community forum](http://community.openab.org/) for help on configuring the device.

**Comment by bredmich** [comment] 2017-09-01 05:47
Are you serious?
That´s what me and some others already tried!
https://community.openhab.org/t/fritzbox-tr064-wan-ip/19634/11

And no one had an idea!

I don´t think the problem is based in my FritzBox.
As other options of the TR-064 binding are working fine.
I´m currently using Callmonitor and Maconline without an problem.

**Comment by 9037568** [comment] 2017-09-01 23:23
The first line of one of your log traces shows the request OH is sending:

2017-08-30 17:40:56.340 [DEBUG] [o.o.b.f.i.FritzboxTr064Binding] - Raw SOAP Request to be sent to FritzBox: <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><u:GetExternalIPAddress xmlns:u="urn:dslforum-org:service:WANPPPConnection:1"/></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by bredmich** [comment] 2017-09-02 15:32
This can´t be the correct SOAP request...

The header is missing:
```
Content-Type: text/xml; charset="utf-8"
SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
```

And the message should be something like:
```
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1" /></s:Body></s:Envelope>
```

Like it´s shown in your link for the curl test.

**Comment by tensberg** [comment] 2017-09-02 19:01
I think bredmich already found the cause of the problem when he wrote

> The binding is trying to get the value "WANPPPConnection".
> I´m not sure if this is the right value for my setup.
> I´m not using the internal DSL modem, i´m using an external cable modem connected to the WAN port. My FritzBox gets the public IPv4 from my modem.
> Maybe the value is "WANIPConnection"...

I use the internal DSL modem and the following curl request to [WANPPPConnection](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wanpppconnSCPD.pdf) returns the IP address as expected:

`curl --anyauth --user youruser:yourpassword http://fritz.box:49000/upnp/control/wanpppconn1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANPPPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANPPPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"`

whereas this request to [WANIPConnection](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wanipconnSCPD.pdf) fails with the "Invalid Action" error:

`curl --anyauth --user youruser:yourpassword http://fritz.box:49000/upnp/control/wanipconn1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANIPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANIPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"`

I guess that it is just the other way round if you use an external modem.

@bredmich : could you try out the curl request above (with your username and password of course ;-) If this is indeed the problem I'll prepare a patch to add support for GetExternalIPAddress to the binding.

**Comment by bredmich** [comment] 2017-09-02 19:54
Hi Michael,

thanks for your help!
One step further :-)

When using WANIPConnection i´m getting the usual error:
```
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription>Invalid Action</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
```

But when i´m using your curl with WANPPPConnection i´m gettingan unauthorized error:
```
<HTML><HEAD><TITLE>401 Unauthorized (ERR_NONE)</TITLE></HEAD><BODY><H1>401 Unauthorized</H1><BR>ERR_NONE<HR><B>Webserver</B> Sat, 02 Sep 2017 19:48:55 GMT</BODY></HTML>
```

But i´m using an FritzBox User with the correct password.
I´m able to login with the combination of user and password to the FritzBox webinterface.

I used this curl:
```
curl --anyauth --user myuser:mypassword http://fritz.box:49000/upnp/control/wanpppconn1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANPPPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANPPPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"
```

**Comment by bredmich** [comment] 2017-09-02 20:09
I think i need to create an authkey, any ideas how to do this?

**Comment by tensberg** [comment] 2017-09-03 10:31
I'm not sure what you mean with an authkey. Usually curl will take care of the authentication details when you use the --anyauth and --user parameters. Maybe you have some special chars in your password which you need to escape when you use it as command-line parameter?

In any case I made a mistake in the curl command-line I gave for the WANIPConnection I gave above, so it was no wonder I got an error. The correct one is:

`curl --anyauth --user youruser:yourpassword http://fritz.box:49000/upnp/control/wanipconnection1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANIPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANIPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"`

(the difference is "wanipconnection1" instead of "wanipconn1")

When I run this command the FritzBox reports a NewExternalIPAddress of 0.0.0.0, which is not surprising as I don't have an external router connected. I still think that would be the service which would have to be used in your case.

@bredmich : could you post the content of http://fritz.box:49000/tr64desc.xml ? This contains all the services your FritzBox supports, and their URLs.

**Comment by bredmich** [comment] 2017-09-03 10:59
AVM says something about an authkey in the TR-064 documentation. The first request will be declined, saying you're unauthenticated. Then you're able to send an request to create this authkey. Sounds similiar to the authentication method for the philips hue.

The password of my openHAB service user got a $ in the password.
What's the correct way of escaping for curl?
Or would it be easier to use an password without any special characters?

I'm going to post the tr64desc later as i'm not at home currently.
Any parts that i should delete before posting?

Thanks
Michael

**Comment by tensberg** [comment] 2017-09-03 13:00
curl (and the fritzboxtr064 binding) uses the standard HTTP digest authentication and handles the exchange internally, so you don't have to worry about it. You don't need to use the similar "Content level authentication" which is described as an alternative to the HTTP auth in the AVM docs.

>The password of my openHAB service user got a $ in the password. What's the correct way of escaping for curl?

$ marks a variable, so it explains why it didn't work. You can simply put the whole `'youruser:yourpassword'` in single quotes (not double quotes) to avoid this.

> Any parts that i should delete before posting?

I don't think so. You might want to delete the <UDN> (unique device name) elements, but I don't know if they are particularly security sensitive. The remaining information should be generic and not particular to your installation.

**Comment by bredmich** [comment] 2017-09-03 19:47
Finally!
The WANIPConnection string works fine :-)
```
curl --anyauth --user 'myuser:my$password' http://fritz.box:49000/upnp/control/wanipconnection1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANIPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANIPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"
```

While WANPPPConnection still gives me the 401 error instead of 0.0.0.0
```
curl --anyauth --user 'myuser:my$password' http://fritz.box:49000/upnp/control/wanpppconn1 -H "Content-Type: text/xml; charset="utf-8"" -H "SoapAction:urn:dslforum-org:service:WANPPPConnection:1#GetExternalIPAddress" -d "<?xml version='1.0' encoding='utf-8'?> <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'> <s:Body> <u:GetExternalIPAddress xmlns:u='urn:dslforum-org:service:WANPPPConnection:1'></u:GetExternalIPAddress> </s:Body> </s:Envelope>"
```

I don´t think we need the tr64desc.xml anymore.
As i already mentioned in my comment, WANIPConnection1 and WANPPPConnection1 are both available.
https://github.com/openhab/openhab1-addons/issues/5283#issuecomment-326382446

1. How do we get my binding fixed?
2. Could you create a global setting to change between IP and PPP with the global binding config?

Thanks
Michael

**Comment by tensberg** [comment] 2017-09-04 18:41
> How do we get my binding fixed?
>  Could you create a global setting to change between IP and PPP with the global binding config?

I've just submitted a pull request which adds a config to get the wan ip via WANIPConnection1 instead of  WANPPPConnection1. If it's accepted, you can change the item configuration for the wan ip from "wanip" to "externalWanip" like this:

`String  fboxWanIPExternal   "FBox external WAN IP [%s]" {fritzboxtr064="externalWanip"}`

When the pull request is merged, you could try out a snapshot build of the FritzBox binding to see if it works. I'll post here when it's available.

> I don´t think we need the tr64desc.xml anymore.
> As i already mentioned in my comment, WANIPConnection1 and WANPPPConnection1 are both available.

Ah yes sorry, I overlooked that you already posted the bits I was interested in. I still wonder why you get the 401 error for the WANPPPConnection1. I guess that's a detail that doesn't really matter now.

**Comment by tensberg** [comment] 2017-09-04 18:44
@9037568 : could you (or another maintainer) add the enhancement label to the issue and perhaps change the summary to "get wan ip from external router" or so?

**Comment by bredmich** [comment] 2017-09-04 20:50
Could you provide me the binding before the normal snapshot build.
I think this will take some time :-)

**Comment by bredmich** [comment] 2017-09-05 19:39
Just tested the pre-build binding and it works just fine.
Thanks @tensberg for your help!

**Closed** 2017-09-09 13:40 UTC
Labels: enhancement
