### ISSUE TITLE
After upgrade from OpenHabian 1.3 to 1.4 OpenHab does not start - MCP23017

### ISSUE THREAD

**Issue by szymic1** [openhab/openhab1-addons#5432] opened 2018-01-11 10:24 UTC
When MCP23017  binding is installed on  Openhaian 1.4 (with OH 2.2), OH cannot start. 

## Expected Behavior
OH should start when I put MCP23017 binding jar in /usr/share/openhab2/addons. 

## Current Behavior
I've tried to install MCP23017 binding (from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/ ). 
but when I copied this to adds directory there are problem with starting Openhab.
Such message appears in log:

```
22017-12-22 08:59:55.498 [ERROR] [org.openhab.binding.mcp23017        ] - FrameworkEvent ERROR - org.openhab.binding.mcp23017
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mcp23017 [19]
  Unresolved requirement: Import-Package: org.openhab.core.binding

        at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```
It happens when system start but it also happen when OH running and I put MCP file on runnnign system. This binding works on OH 2.0 without problem and on 2.1 (after modification described in https://github.com/openhab/openhab1-addons/issues/5237).

## Possible Solution
Only uninstalling MCP binding helps.

## Steps to Reproduce (for bugs)
1. Install Openhabian 1.4 from SD image 
2. Copy  MCP binding file to  /usr/share/openhab2/addons ( download binding from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3 I've used org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar	 newer also does not work)
3. Now you should see openhab.log log messages

## Your Environment
Raspberry 2, Openhabian 1.4, with Razberry hut

Solution from https://github.com/openhab/openhab1-addons/issues/5237 does not work on 1.4

**Comment by 9037568** [comment] 2018-01-11 23:48
Duplicate of #5237.

**Closed by 9037568** 2018-01-11 23:48 UTC
Labels: duplicate
