### ISSUE TITLE
[cups]  there is no printer for path

### ISSUE THREAD

**Issue by andersruberg** [openhab/openhab1-addons#4939] opened 2016-12-28 07:35 UTC
## Expected Behavior
I am expecting the cups binding to find my printer and return the number of jobs in the queue.

## Current Behavior
Cups binding claims it cannot find my printer but the URL is valid. I can reach the printer through web interface as well as with cups4j.runnable-0.6.4.jar. I have disabled authentication in cups policy settings, I have tried using hostname as well as ip in cups settings in openhab.cfg but nothing helps..

```
java -jar cups4j.runnable-0.6.4.jar getPrinters
[main] INFO org.cups4j.test.CupsTest - List printers on localhost:
[main] INFO org.cups4j.test.CupsTest - printer uri=http://localhost:631/printers/laserjet default=true name=laserjet
anders@server:/opt/openhab$ java -jar cups4j.runnable-0.6.4.jar getJobs -P laserjet
[main] INFO org.cups4j.test.CupsTest - job: 6 null completed http://localhost:631/printers/laserjet null

```
Snippet from openhab debug log:
```
265 08:15:03.998 [DEBUG] [.b.cups.internal.CupsActivator:31   ] - Cups binding has been started.
266 08:15:04.009 [DEBUG] [inding.ntp.internal.NtpBinding:84   ] - Got time from ptbtime1.ptb.de: Wednesday, December 28, 2016 8:15:04 AM CET
267 08:15:04.012 [INFO ] [runtime.busevents             :26   ] - Date state updated to 2016-12-28T08:15:04
268 08:15:04.040 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'PrintJobsQueued (Type=NumberItem, State=Uninitialized)' with 'CupsGenericBindingProvider' reader.
269 08:15:04.056 [DEBUG] [.o.b.cups.internal.CupsBinding:84   ] - Connection to CupsServer 127.0.0.1 established
270 08:15:04.060 [DEBUG] [.b.http.internal.HttpActivator:34   ] - HTTP binding has been started.
271 08:15:04.069 [INFO ] [.service.AbstractActiveService:169  ] - Cups Refresh Service has been started
272 08:15:04.116 [INFO ] [.service.AbstractActiveService:169  ] - HTTP Refresh Service has been started
273 08:15:04.889 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet

```
from openhab.cfg:
```
#cups:host=localhost
cups:host=127.0.0.1
#CupsServer Port (optional, defaults to 631)
cups:port=631

```
## Steps to Reproduce (for bugs)
1. Install openhab 1.8.3
2. Install cups and make sure printer is working through cups
3. Configure cups binding
4. Start openhab with ./start_debug.sh to get debug prints

## Context
I am trying to do something similar to
http://tech.sid3windr.be/2015/12/automatically-powering-your-printer-down-with-openhab/

## Your Environment
openhab 1.8.3, ubuntu 12.04, cups 1.7.2

**Comment by 9037568** [comment] 2016-12-29 14:23
I noticed that in your command-line test you used localhost, but your openhab configuration is setup to use 127.0.0.1. Have you tried using localhost in openhab.cfg instead?

(It should make no difference in theory, but ...)

**Comment by andersruberg** [comment] 2016-12-29 15:20
I have tried with "localhost" in openhab.cfg but no difference. Even if I put localhost it will still output the same, i.e.  "there is no printer for path http://127.0.0.1:631/printers/laserjet"

This link reports the same problem. Since I have 1.8.3 I thought this problem was already fixed.
https://groups.google.com/forum/#!topic/openhab/V4LY5L44pTA

**Comment by 9037568** [comment] 2016-12-29 16:22
Well, in this case the problem is coming from [line 138](https://github.com/openhab/openhab/blob/1.8/bundles/binding/org.openhab.binding.cups/src/main/java/org/openhab/binding/cups/internal/CupsBinding.java#L138), where the call to the cups library is failing to return a CupsPrinter object:

````
else {
	printer = client.getPrinter(printerUrl);
}
````

You could try enabling debugging for the cups4j code and see what additional information comes out...

**Comment by 9037568** [comment] 2016-12-29 19:16
Just open up your the logback_debug.xml file and look for the lines like these:

````
	<logger name="org.openhab" level="DEBUG" />
	<logger name="org.openhab.ui" level="INFO" />
	<logger name="org.openhab.ui.webapp" level="DEBUG" />
	<logger name="org.openhab.ui.webapp.internal.servlet" level="INFO" />

````

There will be more than what is shown here, probably.

below that, add another line:
````
<logger name="org.cups4j" level="DEBUG" />
````

Now when you run start_debug, you should get debug output from cups4j, too.

**Comment by andersruberg** [comment] 2017-01-03 22:36
[openhab-cups-debug-log.txt](https://github.com/openhab/openhab/files/683412/openhab-cups-debug-log.txt)

I added `<logger name="org.cups4j" level="DEBUG" />` but cannot see any other debug prints than from the Cubs binding itself. See attached log file.

`/opt/openhab/start_debug.sh | tee ~/temp/openhab-cups-debug-log.txt`

```
cat  ~/temp/openhab-cups-debug-log.txt | grep -ris Cups
23:22:45.396 [DEBUG] [.b.cups.internal.CupsActivator:31   ] - Cups binding has been started.
23:22:45.425 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'PrintJobsQueued (Type=NumberItem, State=Uninitialized)' with 'CupsGenericBindingProvider' reader.
23:22:46.317 [DEBUG] [.o.b.cups.internal.CupsBinding:84   ] - Connection to CupsServer 127.0.0.1 established
23:22:46.333 [INFO ] [.service.AbstractActiveService:169  ] - Cups Refresh Service has been started
23:22:47.911 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:23:17.990 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:23:48.064 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:24:18.139 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:24:48.212 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:25:18.285 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
23:25:48.358 [INFO ] [.o.b.cups.internal.CupsBinding:144  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
```

**Comment by 9037568** [comment] 2017-01-04 00:26
Apparently the cups4j library used by the binding has no logging.

There's a newer version that has logging support. I'll have to see how much work it would be to upgrade to that version...

**Comment by 9037568** [comment] 2017-01-22 15:56
Here's an [updated binding jar](https://drive.google.com/open?id=0B8vYheWfObP9R2ZUN2lySVd2dkE) that uses the newer cups4j library (0.6.4).

Could you try running a debug log with this one, @andersruberg ?

**Comment by andersruberg** [comment] 2017-01-23 19:58
Thanks, however I see no further debugs prints. I have `<logger name="org.cups4j" level="DEBUG" />` in logback_debug.xml and run `./start_debug`. Log attached

<pre>
anders@server:/opt/openhab$ ls -all addons/
total 5308
drwxr-xr-x  2 anders anders      4096 jan 23 20:31 .
drwxr-xr-x 12 anders anders      4096 jan 23 20:31 ..
-rw-r--r--  1 anders familjen   80985 okt 22 11:04 org.openhab.binding.astro-1.8.3.jar
-rwxrw-rw-  1 anders familjen  690614 jan 23 20:29 org.openhab.binding.cups-1.9.0-SNAPSHOT.jar
...
[openhab-cups-debug-new.txt](https://github.com/openhab/openhab1-addons/files/724798/openhab-cups-debug-new.txt)


</pre>

<pre>
anders@server:/opt/openhab$ grep -ris cups /home/anders/temp/openhab-cups-debug-new.log 
20:39:30.840 [DEBUG] [.b.cups.internal.CupsActivator:31   ] - Cups binding has been started.
20:39:30.867 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'PrintJobsQueued (Type=NumberItem, State=Uninitialized)' with 'CupsGenericBindingProvider' reader.
20:39:30.893 [DEBUG] [.o.b.cups.internal.CupsBinding:84   ] - Connection to CupsServer 127.0.0.1 established
20:39:30.920 [INFO ] [.service.AbstractActiveService:169  ] - Cups Refresh Service has been started
20:39:32.613 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
20:40:02.711 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
20:40:32.779 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
20:41:02.852 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
20:41:32.929 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
20:42:03.005 [INFO ] [.o.b.cups.internal.CupsBinding:146  ] - there is no printer for path http://127.0.0.1:631/printers/laserjet
</pre>

**Comment by 9037568** [comment] 2017-01-23 21:25
We may have made this more complicated than it needed to be.

What does your item binding look like?

**Comment by andersruberg** [comment] 2017-01-24 08:49
From defaults.items

`Number PrintJobsQueued "Skrivarjobb i kö: [%d]" {cups="laserjet#NOT_COMPLETED"}`

**Comment by 9037568** [comment] 2017-01-24 15:52
Ok, next question. When you have openhab.cfg set up with localhost:

cups:host=localhost


Does the openhab.log show this error message?

>there is no printer for path http://127.0.0.1:631/printers/laserjet


Or does it say this?

>there is no printer for path http://localhost:631/printers/laserjet

**Comment by andersruberg** [comment] 2017-01-24 20:16
The log shows `there is no printer for path http://127.0.0.1:631/printers/laserjet` no matter if cups:host=localhost or 127.0.0.1

**Comment by 9037568** [comment] 2017-01-25 03:56
Ok. Progress. I think I see the fix for this.

**Comment by 9037568** [comment] 2017-01-25 05:27
The best way to fix this is to alter [line 125 of the CupsBinding](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.cups/src/main/java/org/openhab/binding/cups/internal/CupsBinding.java#L125) to use the configured host value instead of the resolved address.

However, since this binding has been this way for a very long time, I fear that making this change might adversely impact existing installations.

Do any @openhab/maintainers have an opinion on this?

Meanwhile, you might be able to fix this in your setup by using the lpadmin command to change the uri that CUPS has for your printer to be 127.0.0.1 instead of localhost:
````
   lpadmin -p laserjet -v http://127.0.0.1:631/printers/laserjet
````

**Comment by andersruberg** [comment] 2017-01-26 07:18
I tried   ` lpadmin -p laserjet -v http://127.0.0.1:631/printers/laserjet` but it doesn't seem to help me
Still get the same print from cups binding
On the http://127.0.0.1:631/printers/laserjet I see:
<pre>
Description:	Hewlett-Packard HP LaserJet 1018
Location:	server
Driver:	HP LaserJet 1018 Foomatic/foo2zjs-z1 (recommended) (grayscale, 2-sided printing)
Connection:	http://127.0.0.1:631/printers/laserjet
</pre>

 cups4j.runnable:
<pre>
java -jar cups4j.runnable-0.6.4.jar getPrinters
[main] INFO org.cups4j.test.CupsTest - List printers on localhost:
[main] INFO org.cups4j.test.CupsTest - printer uri=http://localhost:631/printers/laserjet default=true name=laserjet
</pre>

**Comment by 9037568** [comment] 2017-01-29 04:18
That's odd. I tried the command and it worked fine, though it did take a minute for the change to show up in printers.conf.

Tomorrow I'll try to create a test jar with the fix I discussed earlier.

**Comment by 9037568** [comment] 2017-01-30 04:36
Try this [experimental jar](https://drive.google.com/open?id=0B8vYheWfObP9TmpOV3c1YUphQzA).

When the binding starts, you should see this INFO message in the log:
````
    Cups binding -- experimental version 20170129T1129
````

If I'm right, this will allow your printer to be found.

**Comment by andersruberg** [comment] 2017-02-02 06:21
The experimental jar works!

<pre>
07:13:47.524 [DEBUG] [.b.cups.internal.CupsActivator:31   ] - Cups binding has been started.
07:13:47.525 [INFO ] [.b.cups.internal.CupsActivator:32   ] - Cups binding -- experimental version 20170129T1129
07:13:48.260 [DEBUG] [.o.b.cups.internal.CupsBinding:84   ] - Connection to CupsServer 127.0.0.1 established
07:13:50.593 [DEBUG] [.o.b.cups.internal.CupsBinding:143  ] - Found printer http://localhost:631/printers/laserjet#NOT_COMPLETED with value 0
07:14:20.652 [DEBUG] [.o.b.cups.internal.CupsBinding:143  ] - Found printer http://localhost:631/printers/laserjet#NOT_COMPLETED with value 0
</pre>

Thanks a lot!

**Comment by andersruberg** [comment] 2017-02-02 06:23
The reason why` lpadmin -p laserjet -v http://127.0.0.1:631/printers/laserjet` didn't work for me is because I have the printer connected to the same machine as where openhab is running and the cups connection needs to be `usb://HP/LaserJet%201018?serial=KP0V7Q7` to be able to print at all.

**Closed** 2017-02-19 13:04 UTC
Labels: bug, pr-submitted
