### ISSUE TITLE
OpenHAB sends 0-bytes files to Dropbox following a change on another device

### ISSUE THREAD

**Issue by slaboure** [openhab/openhab1-addons#3602] opened 2015-12-27 18:37 UTC
Setup:
- 1.7.1 on Odroid XU4, Ubuntu 15.04
- Dropbox setup in BIDIRECTIONAL
- synchronization occuring every minute
  dropbox:uploadInterval=0 0/1 \* \* \* ?
  dropbox:downloadInterval=5 0/1 \* \* \* ?
  dropbox:syncmode=BIDIRECTIONAL

Use Case: 
- modifying one of the config file (bla.items, etc.) on my computer
- change gets sync'ed back to Dropbox
- OpenHAB initiates a sync, so downloads the new version of the remotely modified file
- As soon as done, OpenHAB detects that the same (local) has been modified (even though timestamps have the same value), and send back a "modified" file back to Dropbox but with a ZERO size
- File is not empty on Dropbox and gets sync'ed on my computer as an empty file. Config lost.

Here is a log excerpt of this happening: 

```
2015-12-27 18:19:00.004 [DEBUG] [d.internal.DropboxSynchronizer] - Started synchronization from Dropbox to local ...
2015-12-27 18:19:00.007 [DEBUG] [d.internal.DropboxSynchronizer] - Started synchronization from local to Dropbox ...
2015-12-27 18:19:00.866 [DEBUG] [d.internal.DropboxSynchronizer] - There are '1' deltas to process ...
2015-12-27 18:19:00.928 [DEBUG] [d.internal.DropboxSynchronizer] - There are '32' local entries that met the upload filters ...
2015-12-27 18:19:01.604 [DEBUG] [d.internal.DropboxSynchronizer] - Successfully downloaded file './configurations/sitemaps/default.sitemap'
2015-12-27 18:19:01.605 [DEBUG] [d.internal.DropboxSynchronizer] - '1' deltas met the given downloadFilter [^([^/]*/){1}[^/]*$, /configurations.*]
2015-12-27 18:19:01.874 [DEBUG] [d.internal.DropboxSynchronizer] - Created file '/usr/share/openhab/./deltacursor.dbx' with content 'AAH9CyZ8qzf35fqNiWGNCl4bqznOqbbHEQqvl8HxAkYmetREo3eUyPK9wfexyjMr2qVQCXxdp3EMuJ6MVbjp_acN2SToq6we_3Dptt5ATCRW7F2H0jKHEbJs64rpNJDlRdE'
2015-12-27 18:19:01.941 [DEBUG] [d.internal.DropboxSynchronizer] - successfully uploaded file 'File("/configurations/sitemaps/default.sitemap", iconName="page_white", mightHaveThumbnail=false, numBytes=0, humanSize="0 bytes", lastModified="2015/12/27 18:19:01 UTC", clientMtime="2015/12/27 18:19:01 UTC", rev="464193bb7a")'. New revision is '464193bb7a'
2015-12-27 18:19:01.943 [DEBUG] [d.internal.DropboxSynchronizer] - Deleted cache file './dropbox-entries.dbx' since there are changes. It will be recreated while next synchronization loop.
2015-12-27 18:19:02.205 [DEBUG] [d.internal.DropboxSynchronizer] - Created file '/usr/share/openhab/./deltacursor.dbx' with content 'AAEIHUkcVVAurEOZcjX2ea8_tCMa9Qg-YFNdPOxZHKGvs4aRfaEnq5pKcXVMnOe-eKR_hXyp6VLvWheHbLvamHBBMy0Ez2FbW5eeWXmiIggXxS_AmXV2xGcQXpo1aM5n3h4'
```
##

**Comment by teichsta** [comment] 2015-12-27 18:47
thanks for letting us know @slaboure!

**Comment by 9037568** [comment] 2017-10-04 04:35
Closing due to age. If this can be reproduced using the latest binding snapshot and the most recent official release of either OH1 or OH2, give a shout and I'll reopen it.

**Closed by 9037568** 2017-10-04 04:35 UTC
Labels: bug
